In [1]:
import syft as sy
import numpy as np
from syft.core.adp.data_subject_list import DataSubjectList

In [2]:
from syft.core.tensor.autodp.ndim_entity_phi import NDimEntityPhiTensor as NDEPT
from syft.core.tensor.autodp.gamma_tensor import GammaTensor

In [5]:
ndept = NDEPT(
    child = np.random.randint(low=2, high=100, size=(10,10), dtype=np.int64),
    entities= np.random.choice([0, 1], size=(10, 10)),
    min_vals= 2,
    max_vals= 100
)

In [6]:
ndept

NDimEntityPhiTensor(child=(10, 10), min_vals=<lazyrepeatarray data: 2 -> shape: (10, 10)>, max_vals=<lazyrepeatarray data: 100 -> shape: (10, 10)>)

In [7]:
ndept.gamma

GammaTensor(value=array([[54, 80, 93, 15, 97, 44, 91, 43, 73, 89],
       [84, 50, 38, 21, 56, 44, 91,  7, 60, 44],
       [32, 80, 75, 66, 32, 60, 28, 48, 88, 42],
       [23, 72,  6, 46, 88, 90, 32, 30,  9, 48],
       [34, 79, 57, 85,  2, 56, 62, 81, 98, 66],
       [93, 30,  6, 14, 89, 24, 19, 94, 14, 26],
       [37, 20, 99,  7, 81, 42, 54, 26, 58, 38],
       [27,  7, 87, 82, 32, 88, 90, 96, 17, 86],
       [14, 56, 89,  4, 34, 84, 72, 60, 27, 57],
       [77, 74,  3, 49, 93, 76, 10, 10, 60, 97]]), data_subjects=<syft.core.adp.data_subject_list.DataSubjectList object at 0x7fcfbb6d9490>, min_val=<lazyrepeatarray data: 2 -> shape: (10, 10)>, max_val=<lazyrepeatarray data: 100 -> shape: (10, 10)>, is_linear=True, func=<function no_op at 0x7fcfc1128b80>, id='1239285786', inputs=array([], dtype=int64), state={'1239285786': ...})

In [8]:
tensor1 = ndept + 1

In [10]:
tensor2 = ndept + 7

In [12]:
tensor3 = tensor1 + tensor2

In [16]:
assert (tensor1.child + tensor2.child == tensor3.child).all()

In [18]:
tensor3.entities == tensor1.entities

True

In [19]:
gt = tensor1.gamma + tensor2.gamma

In [20]:
gt

GammaTensor(value=array([[116, 168, 194,  38, 202,  96, 190,  94, 154, 186],
       [176, 108,  84,  50, 120,  96, 190,  22, 128,  96],
       [ 72, 168, 158, 140,  72, 128,  64, 104, 184,  92],
       [ 54, 152,  20, 100, 184, 188,  72,  68,  26, 104],
       [ 76, 166, 122, 178,  12, 120, 132, 170, 204, 140],
       [194,  68,  20,  36, 186,  56,  46, 196,  36,  60],
       [ 82,  48, 206,  22, 170,  92, 116,  60, 124,  84],
       [ 62,  22, 182, 172,  72, 184, 188, 200,  42, 180],
       [ 36, 120, 186,  16,  76, 176, 152, 128,  62, 122],
       [162, 156,  14, 106, 194, 160,  28,  28, 128, 202]]), data_subjects=<syft.core.adp.data_subject_list.DataSubjectList object at 0x7fcfbb6d9490>, min_val=<lazyrepeatarray data: 12 -> shape: (10, 10)>, max_val=<lazyrepeatarray data: 208 -> shape: (10, 10)>, is_linear=True, func=<function GammaTensor.__add__.<locals>._add at 0x7fcfba0a64c0>, id='451898244', inputs=array([], dtype=int64), state={'827855961': GammaTensor(value=array([[ 55,  81,  

In [21]:
gt.state

{'827855961': GammaTensor(value=array([[ 55,  81,  94,  16,  98,  45,  92,  44,  74,  90],
        [ 85,  51,  39,  22,  57,  45,  92,   8,  61,  45],
        [ 33,  81,  76,  67,  33,  61,  29,  49,  89,  43],
        [ 24,  73,   7,  47,  89,  91,  33,  31,  10,  49],
        [ 35,  80,  58,  86,   3,  57,  63,  82,  99,  67],
        [ 94,  31,   7,  15,  90,  25,  20,  95,  15,  27],
        [ 38,  21, 100,   8,  82,  43,  55,  27,  59,  39],
        [ 28,   8,  88,  83,  33,  89,  91,  97,  18,  87],
        [ 15,  57,  90,   5,  35,  85,  73,  61,  28,  58],
        [ 78,  75,   4,  50,  94,  77,  11,  11,  61,  98]]), data_subjects=<syft.core.adp.data_subject_list.DataSubjectList object at 0x7fcfbb6d9490>, min_val=<lazyrepeatarray data: 3 -> shape: (10, 10)>, max_val=<lazyrepeatarray data: 101 -> shape: (10, 10)>, is_linear=True, func=<function no_op at 0x7fcfc1128b80>, id='827855961', inputs=array([], dtype=int64), state={'827855961': ...}),
 '1484962095': GammaTensor(value=arr

In [22]:
gt.state.keys()

dict_keys(['827855961', '1484962095'])

In [24]:
gt.state['827855961'].state

{'827855961': GammaTensor(value=array([[ 55,  81,  94,  16,  98,  45,  92,  44,  74,  90],
        [ 85,  51,  39,  22,  57,  45,  92,   8,  61,  45],
        [ 33,  81,  76,  67,  33,  61,  29,  49,  89,  43],
        [ 24,  73,   7,  47,  89,  91,  33,  31,  10,  49],
        [ 35,  80,  58,  86,   3,  57,  63,  82,  99,  67],
        [ 94,  31,   7,  15,  90,  25,  20,  95,  15,  27],
        [ 38,  21, 100,   8,  82,  43,  55,  27,  59,  39],
        [ 28,   8,  88,  83,  33,  89,  91,  97,  18,  87],
        [ 15,  57,  90,   5,  35,  85,  73,  61,  28,  58],
        [ 78,  75,   4,  50,  94,  77,  11,  11,  61,  98]]), data_subjects=<syft.core.adp.data_subject_list.DataSubjectList object at 0x7fcfbb6d9490>, min_val=<lazyrepeatarray data: 3 -> shape: (10, 10)>, max_val=<lazyrepeatarray data: 101 -> shape: (10, 10)>, is_linear=True, func=<function no_op at 0x7fcfc1128b80>, id='827855961', inputs=array([], dtype=int64), state={'827855961': ...})}

In [26]:
tensor1.entities

In [27]:
tensor1.entities.data_subjects_indexed

array([[0, 1, 0, 1, 1, 1, 1, 0, 0, 0],
       [0, 1, 0, 1, 1, 0, 1, 1, 0, 0],
       [1, 0, 0, 1, 1, 1, 1, 0, 1, 1],
       [1, 0, 0, 0, 1, 0, 1, 0, 0, 0],
       [0, 1, 1, 0, 1, 1, 0, 0, 0, 1],
       [0, 1, 1, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 1, 0, 1],
       [1, 0, 0, 1, 0, 1, 1, 0, 1, 1],
       [0, 0, 0, 1, 1, 1, 0, 1, 1, 0]])

In [28]:
tensor1.entities.one_hot_lookup

array([0, 1])

In [30]:
original_dsi = tensor1.entities.data_subjects_indexed.copy()

In [31]:
new_dsi = np.empty_like(original_dsi)
new_dsi[tensor1.entities.one_hot_lookup] = tensor1.entities.one_hot_lookup + len(tensor1.entities.one_hot_lookup)

ValueError: shape mismatch: value array of shape (2,) could not be broadcast to indexing result of shape (2,10)

In [36]:
original_dsi

array([[0, 1, 0, 1, 1, 1, 1, 0, 0, 0],
       [0, 1, 0, 1, 1, 0, 1, 1, 0, 0],
       [1, 0, 0, 1, 1, 1, 1, 0, 1, 1],
       [1, 0, 0, 0, 1, 0, 1, 0, 0, 0],
       [0, 1, 1, 0, 1, 1, 0, 0, 0, 1],
       [0, 1, 1, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 1, 0, 1],
       [1, 0, 0, 1, 0, 1, 1, 0, 1, 1],
       [0, 0, 0, 1, 1, 1, 0, 1, 1, 0]])

In [37]:
new_dsi = original_dsi + len(tensor1.entities.one_hot_lookup)

In [38]:
new_dsi

array([[2, 3, 2, 3, 3, 3, 3, 2, 2, 2],
       [2, 3, 2, 3, 3, 2, 3, 3, 2, 2],
       [3, 2, 2, 3, 3, 3, 3, 2, 3, 3],
       [3, 2, 2, 2, 3, 2, 3, 2, 2, 2],
       [2, 3, 3, 2, 3, 3, 2, 2, 2, 3],
       [2, 3, 3, 2, 3, 2, 2, 2, 2, 2],
       [2, 3, 3, 3, 3, 2, 2, 3, 2, 2],
       [3, 2, 2, 2, 3, 2, 2, 3, 2, 3],
       [3, 2, 2, 3, 2, 3, 3, 2, 3, 3],
       [2, 2, 2, 3, 3, 3, 2, 3, 3, 2]])

In [39]:
np.searchsorted(tensor1.entities.one_hot_lookup, tensor2.entities.one_hot_lookup)

array([0, 1])

In [46]:
print(np.arange(9), np.arange(8,20))
np.searchsorted(np.arange(9), np.arange(10, 20))

[0 1 2 3 4 5 6 7 8] [ 8  9 10 11 12 13 14 15 16 17 18 19]


array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

In [47]:
len(np.arange(9))

9

In [48]:
np.searchsorted(np.arange(9), np.arange(10, 20)).min()

9

In [59]:
np.concatenate((np.arange(9), np.arange(9) + 9))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [61]:
np.stack((np.arange(9), np.arange(9) + 9))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17]])

In [67]:
search_result = np.searchsorted(np.arange(9), np.arange(6, 20))

In [68]:
search_result

array([6, 7, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

In [69]:
np.where(search_result < len(np.arange(9))) 

(array([0, 1, 2]),)